name: patty
channels:
  - conda-forge
  - defaults
dependencies:
  - antlr-python-runtime=4.12.0=pyhd8ed1ab_0
  - antlr4-python3-runtime=4.12.0=pyh1a96a4e_0
  - func_timeout=4.3.5=py_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - natsort=8.3.1=pyhd8ed1ab_0
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - pip=23.0.1=pyhd8ed1ab_0
  - pylatex=1.4.1=pyh9f0ad1d_0
  - pysmt=0.9.5=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - setuptools=67.6.0=pyhd8ed1ab_0
  - sympy=1.5.1=py37_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - boto3
  - pip:
    - z3-solver==4.8.7.0

